# Generated by Django 3.2.25 on 2024-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitapp', '0002_auto_20240331_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
